name: lite-therm-pose
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy>=1.24
  - matplotlib>=3.8
  - opencv>=4.8
  - pillow>=10
  - pycocotools>=2.0.7
  - pyyaml>=6
  - tqdm>=4.66
